#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define ERR_PARAMETRO -6
#define ERR_NO_FILTRO -5
#define ERR_MEMORIA -4
#define ERR_PROFUNDIDAD -3
#define ERR_ARCHIVO_BMP -2
#define ERR_LECTURA -1
#define TODO_OK 0

#endif // CONSTANTES_H_INCLUDED
